# Generated by Django 5.2.4 on 2026-02-21 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('current_token_number', models.PositiveIntegerField(default=0, help_text='Currently serving')),
                ('last_issued_number', models.PositiveIntegerField(default=0, help_text='Last token generated')),
                ('avg_wait_time_minutes', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('priority', models.BooleanField(default=False, help_text='Senior Citizen / VIP')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving Now'), ('completed', 'Completed'), ('no_show', 'No Show')], default='waiting', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='queues.queuesession')),
            ],
            options={
                'ordering': ['session', 'number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'number'), name='unique_token_per_session')],
            },
        ),
    ]
