# Generated by Django 5.2.4 on 2026-01-05 06:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrasadConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prasad_name', models.CharField(help_text='e.g. Laddu Batch 1', max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prasad_usages', to='inventory.item')),
                ('tenant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prasad_consumptions', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MealToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_tokens', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'date'], name='annadhanam__tenant__c8f300_idx'), models.Index(fields=['tenant', 'token_no'], name='annadhanam__tenant__d19862_idx')],
            },
        ),
    ]
