# Generated by Django 5.2.4 on 2026-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annadhanam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mealtoken',
            name='annadhanam__tenant__c8f300_idx',
        ),
        migrations.RemoveIndex(
            model_name='mealtoken',
            name='annadhanam__tenant__d19862_idx',
        ),
        migrations.RemoveField(
            model_name='mealtoken',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='prasadconsumption',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='mealtoken',
            index=models.Index(fields=['date'], name='annadhanam__date_a48114_idx'),
        ),
        migrations.AddIndex(
            model_name='mealtoken',
            index=models.Index(fields=['token_no'], name='annadhanam__token_n_a9e1ba_idx'),
        ),
    ]
