# Generated by Django 5.2.4 on 2026-04-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annadhanam', '0002_remove_mealtoken_annadhanam__tenant__c8f300_idx_and_more'),
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtoken',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_tokens', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='prasadconsumption',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prasad_consumptions', to='core.tenant'),
        ),
    ]
