# Generated by Django 5.2.4 on 2026-04-14 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Temple Name')),
                ('slug', models.SlugField(help_text='Used for subdomain or unique identifier (e.g. mahadeva-temple)', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='temple_logos/')),
                ('brand_color', models.CharField(default='#6366f1', help_text="Primary color for this temple's dashboard", max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('plan', models.CharField(choices=[('free', 'Free Tier'), ('pro', 'Pro Tier'), ('enterprise', 'Enterprise Tier')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
