# Generated by Django 5.2.4 on 2025-12-30 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devotees', '0001_initial'),
        ('pooja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='devotees.devotee')),
                ('pooja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='pooja.pooja')),
            ],
        ),
    ]
