# Generated by Django 5.2.4 on 2026-01-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_booking_gateway_and_more'),
        ('devotees', '0005_remove_devotee_unique_phone_per_tenant_and_more'),
        ('pooja', '0004_remove_pooja_unique_pooja_name_per_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_receipt_no_per_tenant',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_tenant__cdcc3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_tenant__5546c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_tenant__f609a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_tenant__58bfba_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_tenant__34a813_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_tenant__eb8566_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tenant',
        ),
        migrations.AddField(
            model_name='booking',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='devotee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='devotees.devotee'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='bookings_bo_booking_f34616_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pooja'], name='bookings_bo_pooja_i_b74b15_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['devotee'], name='bookings_bo_devotee_67870a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='bookings_bo_payment_27706e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['source'], name='bookings_bo_source_54090c_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('receipt_no',), name='unique_receipt_no'),
        ),
    ]
