# Generated by Django 5.2.4 on 2026-04-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_unique_receipt_no_per_tenant_and_more'),
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
        ('devotees', '0006_devotee_organization'),
        ('pooja', '0005_remove_pooja_unique_pooja_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_receipt_no',
        ),
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organization'], name='bookings_bo_organiz_a0d680_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('organization', 'receipt_no'), name='unique_receipt_no'),
        ),
    ]
