# Generated by Django 5.2.4 on 2026-04-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_unique_receipt_no_and_more'),
        ('pooja', '0005_remove_pooja_unique_pooja_name_and_more'),
        ('shipments', '0003_prasadamitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prasadam_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='shipments.prasadamitem'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pooja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='pooja.pooja'),
        ),
    ]
