# Generated by Django 5.2.4 on 2026-04-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_prasadam_item_alter_booking_pooja'),
        ('finance', '0006_transaction_payment_mode_bankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='finance.bankaccount'),
        ),
    ]
