# Generated by Django 5.2.4 on 2026-01-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_digital_passes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=0, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='event',
            name='pass_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per entry pass', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', 'start_date'], name='events_even_tenant__323e90_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', 'is_active'], name='events_even_tenant__fba2ba_idx'),
        ),
    ]
