# Generated by Django 5.2.4 on 2026-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_enable_digital_passes_event_max_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_tenant__323e90_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_tenant__fba2ba_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='events_even_is_acti_82811f_idx'),
        ),
    ]
