# Generated by Django 5.2.4 on 2026-04-13 08:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Traditional Golden Crown', max_length=200)),
                ('asset_id', models.CharField(help_text='Internal tracking number', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('valuation', models.DecimalField(decimal_places=2, default=0, help_text='Estimated market value', max_digits=15)),
                ('status', models.CharField(choices=[('healthy', 'Healthy/Fine'), ('damaged', 'Needs Repair'), ('maintenance', 'Under Cleaning/Service'), ('lost', 'Missing/Lost')], default='healthy', max_length=20)),
                ('location', models.CharField(help_text='e.g. Locker A, Sanctum Sanctorum', max_length=150)),
                ('custodian', models.CharField(blank=True, help_text='Who is currently responsible for it', max_length=100)),
                ('maintenance_interval_days', models.IntegerField(default=90, help_text='How often should this be cleaned/serviced?')),
                ('last_maintained_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(default=datetime.date.today)),
                ('performer', models.CharField(help_text='Who performed the service', max_length=150)),
                ('activity', models.TextField(help_text='e.g. Silver polishing using traditional oils')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_planned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='assets.asset')),
            ],
        ),
    ]
