# Generated by Django 5.2.4 on 2026-04-17 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0005_plan_razorpay_plan_id_tenant_razorpay_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='core.tenant'),
        ),
    ]
