# Generated by Django 5.2.4 on 2026-04-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_maintenancelog_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='service_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
