# Generated by Django 5.2.4 on 2026-01-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='tenant',
        ),
    ]
