# Generated by Django 5.2.4 on 2025-12-30 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('pooja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja',
            name='festival_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festival_poojas', to='events.event'),
        ),
        migrations.AddField(
            model_name='pooja',
            name='is_festival_special',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PoojaTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pooja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='pooja.pooja')),
                ('priest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pooja_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('pooja', 'start_time')},
            },
        ),
    ]
