# Generated by Django 5.2.4 on 2026-01-05 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0002_event_enable_digital_passes_event_max_capacity_and_more'),
        ('pooja', '0002_pooja_festival_event_pooja_is_festival_special_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poojatimeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pooja',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poojas', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='poojatimeslot',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pooja_slots', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='pooja',
            index=models.Index(fields=['tenant', 'name'], name='pooja_pooja_tenant__cb6d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='pooja',
            index=models.Index(fields=['tenant', 'is_active'], name='pooja_pooja_tenant__6b4add_idx'),
        ),
        migrations.AddIndex(
            model_name='poojatimeslot',
            index=models.Index(fields=['tenant', 'pooja', 'start_time'], name='pooja_pooja_tenant__bb8a52_idx'),
        ),
        migrations.AddIndex(
            model_name='poojatimeslot',
            index=models.Index(fields=['tenant', 'start_time'], name='pooja_pooja_tenant__838617_idx'),
        ),
        migrations.AddConstraint(
            model_name='pooja',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_pooja_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='poojatimeslot',
            constraint=models.UniqueConstraint(fields=('tenant', 'pooja', 'start_time'), name='unique_slot_per_pooja_per_tenant'),
        ),
    ]
