# Generated by Django 5.2.4 on 2026-01-05 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_events_even_tenant__323e90_idx_and_more'),
        ('pooja', '0003_alter_poojatimeslot_unique_together_pooja_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pooja',
            name='unique_pooja_name_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='poojatimeslot',
            name='unique_slot_per_pooja_per_tenant',
        ),
        migrations.RemoveIndex(
            model_name='pooja',
            name='pooja_pooja_tenant__cb6d7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='pooja',
            name='pooja_pooja_tenant__6b4add_idx',
        ),
        migrations.RemoveIndex(
            model_name='poojatimeslot',
            name='pooja_pooja_tenant__bb8a52_idx',
        ),
        migrations.RemoveIndex(
            model_name='poojatimeslot',
            name='pooja_pooja_tenant__838617_idx',
        ),
        migrations.RemoveField(
            model_name='pooja',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='poojatimeslot',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='pooja',
            index=models.Index(fields=['name'], name='pooja_pooja_name_dc922c_idx'),
        ),
        migrations.AddIndex(
            model_name='pooja',
            index=models.Index(fields=['is_active'], name='pooja_pooja_is_acti_5636e1_idx'),
        ),
        migrations.AddIndex(
            model_name='poojatimeslot',
            index=models.Index(fields=['pooja', 'start_time'], name='pooja_pooja_pooja_i_96a8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='poojatimeslot',
            index=models.Index(fields=['start_time'], name='pooja_pooja_start_t_a576d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='pooja',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_pooja_name'),
        ),
        migrations.AddConstraint(
            model_name='poojatimeslot',
            constraint=models.UniqueConstraint(fields=('pooja', 'start_time'), name='unique_slot_per_pooja'),
        ),
    ]
