# Generated by Django 5.2.4 on 2026-04-09 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
        ('events', '0004_event_organization'),
        ('pooja', '0004_remove_pooja_unique_pooja_name_per_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pooja',
            name='unique_pooja_name',
        ),
        migrations.RemoveConstraint(
            model_name='poojatimeslot',
            name='unique_slot_per_pooja',
        ),
        migrations.AddField(
            model_name='pooja',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poojas', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='poojatimeslot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pooja_slots', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='pooja',
            index=models.Index(fields=['organization'], name='pooja_pooja_organiz_8743f3_idx'),
        ),
        migrations.AddIndex(
            model_name='poojatimeslot',
            index=models.Index(fields=['organization'], name='pooja_pooja_organiz_194500_idx'),
        ),
        migrations.AddConstraint(
            model_name='pooja',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_pooja_name'),
        ),
        migrations.AddConstraint(
            model_name='poojatimeslot',
            constraint=models.UniqueConstraint(fields=('organization', 'pooja', 'start_time'), name='unique_slot_per_pooja'),
        ),
    ]
