# Generated by Django 5.2.4 on 2026-04-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0005_remove_pooja_unique_pooja_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pooja',
            name='description',
        ),
    ]
