# Generated by Django 5.2.4 on 2026-04-23 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0006_remove_pooja_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
