# Generated by Django 5.2.4 on 2026-04-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_remove_auditlog_tenant'),
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant'),
        ),
    ]
