# Generated by Django 5.2.4 on 2025-12-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devotees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(blank=True, max_length=150)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank', 'Bank Transfer')], default='cash', max_length=20)),
                ('receipt_no', models.CharField(max_length=30, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='devotees.devotee')),
            ],
        ),
    ]
