# Generated by Django 5.2.4 on 2026-01-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('devotees', '0004_alter_devotee_tenant_alter_devotee_updated_at_and_more'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donated_at'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AddField(
            model_name='donation',
            name='display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='donation',
            name='gateway',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='donation',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='gst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_gst_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_qr/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='qr_payload',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('wallet', 'Wallet'), ('bank', 'Bank Transfer')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='DonationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_categories', to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.donationcategory'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['tenant', 'donated_at'], name='donations_d_tenant__1ac1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['tenant', 'payment_status'], name='donations_d_tenant__6d0f53_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['tenant', 'payment_mode'], name='donations_d_tenant__228343_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['tenant', 'devotee'], name='donations_d_tenant__634d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['tenant', 'category'], name='donations_d_tenant__617c8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_no__isnull', False)), fields=('tenant', 'receipt_no'), name='unique_donation_receipt_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='donationcategory',
            index=models.Index(fields=['tenant', 'name'], name='donations_d_tenant__e9b637_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcategory',
            index=models.Index(fields=['tenant', 'is_active'], name='donations_d_tenant__7b5373_idx'),
        ),
        migrations.AddConstraint(
            model_name='donationcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_donation_category_per_tenant'),
        ),
    ]
