# Generated by Django 5.2.4 on 2026-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0005_remove_devotee_unique_phone_per_tenant_and_more'),
        ('donations', '0002_alter_donation_options_donation_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='donation',
            name='unique_donation_receipt_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='donationcategory',
            name='unique_donation_category_per_tenant',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_tenant__1ac1b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_tenant__6d0f53_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_tenant__228343_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_tenant__634d3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_tenant__617c8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='donationcategory',
            name='donations_d_tenant__e9b637_idx',
        ),
        migrations.RemoveIndex(
            model_name='donationcategory',
            name='donations_d_tenant__7b5373_idx',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='donationcategory',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='donationcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donated_at'], name='donations_d_donated_7b0c04_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_status'], name='donations_d_payment_453297_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_mode'], name='donations_d_payment_784466_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['devotee'], name='donations_d_devotee_4f9db4_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['category'], name='donations_d_categor_6361e2_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcategory',
            index=models.Index(fields=['is_active'], name='donations_d_is_acti_904809_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.UniqueConstraint(fields=('receipt_no',), name='unique_donation_receipt'),
        ),
        migrations.AddConstraint(
            model_name='donationcategory',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_donation_category'),
        ),
    ]
