# Generated by Django 5.2.4 on 2026-04-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
        ('devotees', '0006_devotee_organization'),
        ('donations', '0003_remove_donation_unique_donation_receipt_per_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='donation',
            name='unique_donation_receipt',
        ),
        migrations.RemoveConstraint(
            model_name='donationcategory',
            name='unique_donation_category',
        ),
        migrations.AddField(
            model_name='donation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='donationcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_categories', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['organization'], name='donations_d_organiz_7049c2_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcategory',
            index=models.Index(fields=['organization'], name='donations_d_organiz_d2ada2_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.UniqueConstraint(fields=('organization', 'receipt_no'), name='unique_donation_receipt'),
        ),
        migrations.AddConstraint(
            model_name='donationcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_donation_category'),
        ),
    ]
