# Generated by Django 5.2.4 on 2026-04-12 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0009_remove_gothra_unique_gothra_and_more'),
        ('donations', '0004_remove_donation_unique_donation_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='devotee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='devotees.devotee'),
        ),
    ]
