# Generated by Django 5.2.4 on 2026-04-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_donation_devotee'),
        ('finance', '0006_transaction_payment_mode_bankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='finance.bankaccount'),
        ),
    ]
