# Generated by Django 5.2.4 on 2026-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_tenant__d80b5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_tenant__e7e716_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='finance_tra_date_f21d66_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['txn_type'], name='finance_tra_txn_typ_cba896_idx'),
        ),
    ]
