# Generated by Django 5.2.4 on 2026-04-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
        ('finance', '0003_remove_transaction_finance_tra_tenant__d80b5f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.tenant'),
        ),
    ]
