# Generated by Django 5.2.4 on 2026-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('ritual_fees', 'Ritual Fees (Income)'), ('donation_general', 'Donations (Income)'), ('hundi_collection', 'Hundi Collection (Income)'), ('staff_salary', 'Staff Salary (Expense)'), ('temple_maintenance', 'Maintenance (Expense)'), ('stock_purchase', 'Inventory/Stock (Expense)'), ('utility_bills', 'Utilities/Bills (Expense)'), ('other', 'Other Miscellaneous')], default='other', max_length=30),
        ),
    ]
