# Generated by Django 5.2.4 on 2026-01-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='purchase_bills/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='opening_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.itemcategory'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'name'], name='inventory_i_tenant__f2ca84_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'is_active'], name='inventory_i_tenant__09634c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'category'], name='inventory_i_tenant__257b1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_item_name_per_tenant'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='inventory.purchase'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['tenant', 'created_at'], name='inventory_s_tenant__38fc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['tenant', 'item'], name='inventory_s_tenant__e6df12_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['tenant', 'txn_type'], name='inventory_s_tenant__351fe6_idx'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.vendor'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['tenant', 'name'], name='inventory_i_tenant__3a2149_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['tenant', 'is_active'], name='inventory_i_tenant__4a9d2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_item_category_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['tenant', 'name'], name='inventory_v_tenant__88775d_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_vendor_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'vendor'], name='inventory_p_tenant__862d28_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'invoice_date'], name='inventory_p_tenant__100210_idx'),
        ),
    ]
