# Generated by Django 5.2.4 on 2026-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchase_vendor_alter_stocktransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_name_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='itemcategory',
            name='unique_item_category_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_vendor_name_per_tenant',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='inventory_i_tenant__f2ca84_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='inventory_i_tenant__09634c_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='inventory_i_tenant__257b1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemcategory',
            name='inventory_i_tenant__3a2149_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemcategory',
            name='inventory_i_tenant__4a9d2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='inventory_p_tenant__862d28_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='inventory_p_tenant__100210_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocktransaction',
            name='inventory_s_tenant__38fc1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocktransaction',
            name='inventory_s_tenant__e6df12_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocktransaction',
            name='inventory_s_tenant__351fe6_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='inventory_v_tenant__88775d_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='inventory_i_name_637656_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active'], name='inventory_i_is_acti_fd4174_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='inventory_i_categor_dcc1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['name'], name='inventory_i_name_9b7fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['is_active'], name='inventory_i_is_acti_b6d795_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['vendor'], name='inventory_p_vendor__0ad4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['invoice_date'], name='inventory_p_invoice_de9498_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['created_at'], name='inventory_s_created_ff5dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['item'], name='inventory_s_item_id_cb90d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['txn_type'], name='inventory_s_txn_typ_ca844b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='inventory_v_name_f75e09_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_item_name'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_item_category'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_vendor_name'),
        ),
    ]
