# Generated by Django 5.2.4 on 2026-04-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
        ('inventory', '0003_remove_item_unique_item_name_per_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_name',
        ),
        migrations.RemoveConstraint(
            model_name='itemcategory',
            name='unique_item_category',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_vendor_name',
        ),
        migrations.AddField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['organization'], name='inventory_i_organiz_830d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['organization'], name='inventory_i_organiz_6070b4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['organization'], name='inventory_p_organiz_aec48e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['organization'], name='inventory_s_organiz_9e2041_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['organization'], name='inventory_v_organiz_c7575f_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_item_name'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_item_category'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_vendor_name'),
        ),
    ]
