# Generated by Django 5.2.4 on 2026-04-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_item_unique_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
