# Generated by Django 5.2.4 on 2026-04-22 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction_payment_mode_bankaccount_and_more'),
        ('inventory', '0005_stocktransaction_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_purchases', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank'), ('card', 'Card')], default='cash', max_length=20),
        ),
    ]
