# Generated by Django 5.2.4 on 2026-01-05 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HundiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Weekly Hundi Opening - Jan Week 1', max_length=150)),
                ('opening_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('counting', 'Counting In Progress'), ('closed', 'Closed & Verified')], default='open', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('proof_attachment', models.FileField(blank=True, null=True, upload_to='hundi_proofs/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hundi_sessions', to='core.tenant')),
            ],
            options={
                'ordering': ['-opening_date'],
            },
        ),
        migrations.CreateModel(
            name='HundiWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name if not a system user', max_length=150)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='hundi.hundisession')),
                ('tenant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hundi_witnesses', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hundi Witnesses',
            },
        ),
        migrations.CreateModel(
            name='HundiCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.PositiveIntegerField(choices=[(500, '500'), (200, '200'), (100, '100'), (50, '50'), (20, '20'), (10, '10'), (5, '5'), (2, '2'), (1, '1')])),
                ('count', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('tenant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hundi_collections', to='core.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='hundi.hundisession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'denomination'), name='unique_denomination_per_session')],
            },
        ),
    ]
