# Generated by Django 5.2.4 on 2026-01-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hundi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hundicollection',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='hundisession',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='hundiwitness',
            name='tenant',
        ),
    ]
