# Generated by Django 5.2.4 on 2026-04-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction_payment_mode_bankaccount_and_more'),
        ('hundi', '0003_hundisession_organization_hundiwitness_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='hundisession',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hundi_sessions', to='finance.bankaccount'),
        ),
    ]
