# Generated by Django 5.2.4 on 2026-04-23 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hundi', '0004_hundisession_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hundisession',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
