# Generated by Django 5.2.4 on 2025-12-30 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gothra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nakshatra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='devotee',
            name='id_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='devotee',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='devotee',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('aadhar', 'Aadhar'), ('pan', 'PAN'), ('voter', 'Voter ID'), ('driving_license', 'Driving License'), ('passport', 'Passport'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='devotee',
            name='gothra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devotees.gothra'),
        ),
        migrations.AddField(
            model_name='devotee',
            name='nakshatra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devotees.nakshatra'),
        ),
    ]
