# Generated by Django 5.2.4 on 2026-01-01 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('devotees', '0002_gothra_nakshatra_devotee_id_proof_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devotee',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devotees', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devotee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gothra',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gothras', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nakshatra',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nakshatras', to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devotee',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='gothra',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nakshatra',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='devotee',
            index=models.Index(fields=['tenant', 'phone'], name='devotees_de_tenant__0cc242_idx'),
        ),
        migrations.AddIndex(
            model_name='devotee',
            index=models.Index(fields=['tenant', 'full_name'], name='devotees_de_tenant__90f3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='devotee',
            index=models.Index(fields=['tenant', 'created_at'], name='devotees_de_tenant__4b4a77_idx'),
        ),
        migrations.AddIndex(
            model_name='gothra',
            index=models.Index(fields=['tenant', 'name'], name='devotees_go_tenant__b92d74_idx'),
        ),
        migrations.AddIndex(
            model_name='nakshatra',
            index=models.Index(fields=['tenant', 'name'], name='devotees_na_tenant__52da10_idx'),
        ),
        migrations.AddConstraint(
            model_name='devotee',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='unique_phone_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='gothra',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_gothra_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='nakshatra',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_nakshatra_per_tenant'),
        ),
    ]
