# Generated by Django 5.2.4 on 2026-01-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('devotees', '0003_devotee_tenant_devotee_updated_at_gothra_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotee',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devotees', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gothra',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gothras', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='nakshatra',
            name='tenant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nakshatras', to='core.tenant'),
        ),
    ]
