# Generated by Django 5.2.4 on 2026-01-05 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0004_alter_devotee_tenant_alter_devotee_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='devotee',
            name='unique_phone_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='gothra',
            name='unique_gothra_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='nakshatra',
            name='unique_nakshatra_per_tenant',
        ),
        migrations.RemoveIndex(
            model_name='devotee',
            name='devotees_de_tenant__0cc242_idx',
        ),
        migrations.RemoveIndex(
            model_name='devotee',
            name='devotees_de_tenant__90f3d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='devotee',
            name='devotees_de_tenant__4b4a77_idx',
        ),
        migrations.RemoveIndex(
            model_name='gothra',
            name='devotees_go_tenant__b92d74_idx',
        ),
        migrations.RemoveIndex(
            model_name='nakshatra',
            name='devotees_na_tenant__52da10_idx',
        ),
        migrations.RemoveField(
            model_name='devotee',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='gothra',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='nakshatra',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='devotee',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AddIndex(
            model_name='devotee',
            index=models.Index(fields=['phone'], name='devotees_de_phone_81a8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='devotee',
            index=models.Index(fields=['full_name'], name='devotees_de_full_na_c8250f_idx'),
        ),
        migrations.AddIndex(
            model_name='devotee',
            index=models.Index(fields=['created_at'], name='devotees_de_created_6755f5_idx'),
        ),
        migrations.AddIndex(
            model_name='gothra',
            index=models.Index(fields=['name'], name='devotees_go_name_e07c27_idx'),
        ),
        migrations.AddIndex(
            model_name='nakshatra',
            index=models.Index(fields=['name'], name='devotees_na_name_58bb2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='gothra',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_gothra'),
        ),
        migrations.AddConstraint(
            model_name='nakshatra',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_nakshatra'),
        ),
    ]
