# Generated by Django 5.2.4 on 2026-04-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
        ('devotees', '0005_remove_devotee_unique_phone_per_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devotees', to='core.tenant'),
        ),
    ]
