# Generated by Django 5.2.4 on 2026-04-11 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
        ('devotees', '0006_devotee_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
#        migrations.RemoveIndex(
#            model_name='devotee',
#            name='devotees_de_phone_81a8cb_idx',
#        ),
        migrations.AlterField(
            model_name='devotee',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AddIndex(
            model_name='devotee',
            index=models.Index(fields=['organization', 'phone'], name='devotees_de_organiz_833f6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='devotee',
            constraint=models.UniqueConstraint(fields=('organization', 'phone'), name='unique_devotee_phone_per_tenant'),
        ),
    ]
