# Generated by Django 5.2.4 on 2026-04-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0007_remove_devotee_devotees_de_phone_81a8cb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='devotee',
            name='devotees_de_phone_81a8cb_idx',
        ),
    ]
