# Generated by Django 5.2.4 on 2026-04-12 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
        ('devotees', '0008_remove_devotee_devotees_de_phone_81a8cb_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gothra',
            name='unique_gothra',
        ),
        migrations.RemoveConstraint(
            model_name='nakshatra',
            name='unique_nakshatra',
        ),
        migrations.AddField(
            model_name='gothra',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gothras', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='nakshatra',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nakshatras', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='gothra',
            index=models.Index(fields=['organization'], name='devotees_go_organiz_e9ec48_idx'),
        ),
        migrations.AddIndex(
            model_name='nakshatra',
            index=models.Index(fields=['organization'], name='devotees_na_organiz_c15c43_idx'),
        ),
        migrations.AddConstraint(
            model_name='gothra',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_gothra'),
        ),
        migrations.AddConstraint(
            model_name='nakshatra',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_nakshatra'),
        ),
    ]
