# Generated by Django 5.2.4 on 2026-04-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0009_remove_gothra_unique_gothra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gothra',
            name='name_ml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nakshatra',
            name='name_ml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
