# Generated by Django 5.2.4 on 2026-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0010_gothra_name_ml_nakshatra_name_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotee',
            name='is_trust_member',
            field=models.BooleanField(default=False),
        ),
    ]
