# Generated by Django 5.2.4 on 2026-04-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0011_devotee_is_trust_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotee',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('aadhar', 'Aadhar'), ('pan', 'PAN')], max_length=30),
        ),
    ]
