# Generated by Django 5.2.4 on 2026-04-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0012_alter_devotee_id_proof_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotee',
            name='family_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='devotees.devotee'),
        ),
    ]
