# Generated by Django 5.2.4 on 2026-04-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_remove_booking_unique_receipt_no_and_more'),
        ('core', '0003_tenant_address_tenant_brand_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrasadShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_partner', models.CharField(blank=True, help_text='e.g. BlueDart, Delhivery, India Post', max_length=100)),
                ('tracking_id', models.CharField(blank=True, max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('shipping_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Preparation'), ('prepared', 'Prasad Prepared'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='bookings.booking')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='shipments_p_organiz_ced5f3_idx'), models.Index(fields=['status'], name='shipments_p_status_1875b5_idx'), models.Index(fields=['tracking_id'], name='shipments_p_trackin_bbce2d_idx')],
            },
        ),
    ]
