# Generated by Django 5.2.4 on 2026-04-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plan_razorpay_plan_id_tenant_razorpay_customer_id_and_more'),
        ('shipments', '0002_alter_prasadshipment_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrasadamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prasadam_items', to='core.tenant')),
            ],
        ),
    ]
