# Generated by Django 5.2.4 on 2026-04-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_prasadamitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prasadamitem',
            name='expiry_days',
            field=models.IntegerField(default=30, help_text='Shelf life in days'),
        ),
    ]
