# Generated by Django 5.2.4 on 2026-04-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('temple_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('interested_plan', models.CharField(choices=[('lite', 'Lite Plan'), ('pro', 'Pro Heritage'), ('ultimate', 'Ultimate Devaswom')], default='pro', max_length=50)),
                ('is_responded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Heritage Lead',
                'verbose_name_plural': 'Heritage Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
