# Generated by Django 5.2.4 on 2026-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='trial_requested',
            field=models.BooleanField(default=False),
        ),
    ]
