# Generated by Django 5.2.4 on 2026-04-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_latitude_lead_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='interested_plan',
            field=models.CharField(choices=[('LITE', 'Lite Plan'), ('PRO', 'Pro Heritage'), ('MAX', 'Ultimate Devaswom')], default='PRO', max_length=50),
        ),
    ]
