# Generated by Django 5.2.4 on 2025-12-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('temple_admin', 'Temple Admin'), ('accountant', 'Accountant'), ('priest', 'Priest'), ('counter_staff', 'Counter Staff'), ('volunteer', 'Volunteer'), ('devotee', 'Devotee')], default='devotee', max_length=20),
        ),
    ]
