# Generated by Django 5.2.4 on 2026-01-05 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('half_day', 'Half Day')], default='present', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='users_atten_user_id_a911bf_idx'), models.Index(fields=['date', 'status'], name='users_atten_date_f46f41_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_attendance_per_user_per_day')],
            },
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning (6am-2pm)'), ('evening', 'Evening (2pm-10pm)'), ('full', 'Full Day')], max_length=20)),
                ('area', models.CharField(help_text='e.g. Sanctum, Counter, Hundi', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_rosters', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'shift'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='users_dutyr_tenant__bf0026_idx'), models.Index(fields=['tenant', 'user'], name='users_dutyr_tenant__811d4d_idx')],
            },
        ),
    ]
