# Generated by Django 5.2.4 on 2026-01-05 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_attendance_dutyroster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dutyroster',
            name='users_dutyr_tenant__bf0026_idx',
        ),
        migrations.RemoveIndex(
            model_name='dutyroster',
            name='users_dutyr_tenant__811d4d_idx',
        ),
        migrations.RemoveField(
            model_name='dutyroster',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['date'], name='users_dutyr_date_a8fbf8_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['user'], name='users_dutyr_user_id_89c4d4_idx'),
        ),
    ]
