# Generated by Django 5.2.4 on 2026-02-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_dutyroster_users_dutyr_tenant__bf0026_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
