# Generated by Django 5.2.4 on 2026-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_attendance_is_verified_attendance_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_wage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
