# Generated by Django 5.2.4 on 2026-01-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LITE', 'Lite'), ('PRO', 'Pro'), ('PRO_MAX', 'Pro Max')], max_length=20, unique=True)),
                ('allowed_apps', models.JSONField(default=list, help_text='List of app labels allowed for this plan')),
            ],
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='code',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phone',
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_name',
            field=models.CharField(default=1, help_text='Unique DB identifier for this tenant', max_length=63, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(default=1, max_length=63, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plan'),
        ),
    ]
