# Generated by Django 5.2.4 on 2026-04-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plan_razorpay_plan_id_tenant_razorpay_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='authorized_signatory_designation',
            field=models.CharField(blank=True, help_text='Official designation (e.g., Executive Officer)', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='authorized_signatory_name',
            field=models.CharField(blank=True, help_text='Name of the official signing receipts (e.g., K. Balakrishnan)', max_length=150),
        ),
    ]
