# Generated by Django 5.2.4 on 2026-04-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenant_authorized_signatory_designation_and_more'),
        ('core', '0006_tenant_status_subscriptionrequest'),
    ]

    operations = [
    ]
